server:
  port: 433
  address: 127.0.0.1
  http2:
    enabled: true

lavalink:
  server:
    password: "hellen"
    bufferDurationMS: 400
    opusEncodingQuality: 10
    resamplingQuality: MEDIUM
    sources:
      youtube: false  
      bandcamp: false
      soundcloud: false
      spotify: true
      twitch: false
      vimeo: false
      nico: false
      http: false
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 2
    youtubeSearchEnabled: false
    soundcloudSearchEnabled: false
    gc-warnings: true
  spotifyConfig:
    clientId: "2a56091b6217412f835a057da569605d"
    clientSecret: "ea106828a0914740bf7ea11e795f708c"
    countryCode: "ID"
    spDC: "AQDQD6U5yVmcPkrW75BKAxJ4p-bRmcYB1fIqLu1mUdUgXpF_mSzePvcTVUp8xvTg1JhsUZRyXMuL9812xo_alFPWfegC8sBtXuQunwYW0DBdXXYShsRItgA-hy0GBRsvaL6TIwrEHQiCe0jxGJIk1fbLKyfZJ6nyD1ENQOu0b16liUw0wqPC8Dfqa0bpN7rPpeg7afMkw_DQyhGDLg"


  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.4"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.0"
      snapshot: false

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - WEB
      - MUSIC
      - WEBEMBEDDED
    clientOptions:
      WEB:
        playback: true
        videoLoading: false
      WEBEMBEDDED:
        playlistLoading: false
        searching: false
  spotify:
    enabled: true
    allowSearch: true
    allowDirectPlaylistIds: true
    clients:
      - WEB
      - MUSIC
      - WEBEMBEDDED

  lavasrc:
    providers:
      - "spsearch:"
      - "ytsearch:"
    sources:
      spotify: true
      youtube: true
    spotify:
      clientId: "2a56091b6217412f835a057da569605d"
      clientSecret: "ea106828a0914740bf7ea11e795f708c"
      spDC: "AQDQD6U5yVmcPkrW75BKAxJ4p-bRmcYB1fIqLu1mUdUgXpF_mSzePvcTVUp8xvTg1JhsUZRyXMuL9812xo_alFPWfegC8sBtXuQunwYW0DBdXXYShsRItgA-hy0GBRsvaL6TIwrEHQiCe0jxGJIk1fbLKyfZJ6nyD1ENQOu0b16liUw0wqPC8Dfqa0bpN7rPpeg7afMkw_DQyhGDLg"
      countryCode: "US"   # default negara (bisa ID, US, dll.)
      preferAnonymousToken: false
      customTokenEndpoint: "https://accounts.spotify.com/api/token" 
      playlistLoadLimit: 10
      albumLoadLimit: 10
      resolveArtistsInSearch: true
      localFiles: false
    lyrics-sources:
      spotify: false
      youtube: false

metrics:
  prometheus:
    enabled: false

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO

  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000

  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
